<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class XeMaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('xe_may')->insert([
            [
                'id_xe' => 5,
                'hinh_anh' => 'https://product.hstatic.net/200000560101/product/alpha_490c985a1d364ba4b6dda4207be9ab3a.png',
                'bien_so' => null,
                'dong_xe' => 'Xe số',
                'ten_xe' => 'Wawe Alpha',
                'gia' => 20000000,
                'mau_sac' => 'Đỏ, Xanh',
                'so_khung' => 'FDB SD',
                'so_may' => 'DFVZD',
                'loai_xe' => '1',
                'tinh_nang' => 'Phanh đĩa, Động cơ mạnh mẽ',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế gọn nhẹ',
                'tienich_antoan' => 'Hệ thống chống trộm',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-29 15:22:04',
            ],
            [
                'id_xe' => 6,
                'hinh_anh' => 'https://motosaigon.vn/wp-content/uploads/2021/10/honda-future-125-2022-moi-danh-gia-xe-motosaigon-4.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe số',
                'ten_xe' => 'Future 125',
                'gia' => 35000000,
                'mau_sac' => 'Xanh, Đỏ',
                'so_khung' => 'KH654321',
                'so_may' => 'SM112233',
                'loai_xe' => '1',
                'tinh_nang' => 'Phanh đĩa, Động cơ 125cc',
                'cong_nghe' => 'Công nghệ tiết kiệm xăng',
                'thiet_ke' => 'Thiết kế hiện đại',
                'tienich_antoan' => 'Hệ thống an toàn ABS',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 7,
                'hinh_anh' => 'https://livingwithgravity.com/wp-content/uploads/2021/04/Honda-supercub-6.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe số',
                'ten_xe' => 'Supercub 125',
                'gia' => 45000000,
                'mau_sac' => 'Trắng, Đen',
                'so_khung' => 'KH789012',
                'so_may' => 'SM223344',
                'loai_xe' => '1',
                'tinh_nang' => 'Động cơ mạnh mẽ, Tiết kiệm nhiên liệu',
                'cong_nghe' => 'Công nghệ phun xăng điện tử',
                'thiet_ke' => 'Thiết kế cổ điển',
                'tienich_antoan' => 'Chống trộm, khóa an toàn',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 8,
                'hinh_anh' => 'http://cms-i.autodaily.vn/du-lieu/2017/12/07/3-mau-xe-moi-honda-autodaily-3.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe số',
                'ten_xe' => 'Honda Blade 110',
                'gia' => 24000000,
                'mau_sac' => 'Đỏ, Xanh',
                'so_khung' => 'KH345678',
                'so_may' => 'SM556677',
                'loai_xe' => '1',
                'tinh_nang' => 'Phanh đĩa, Động cơ 110cc',
                'cong_nghe' => 'Công nghệ tiết kiệm xăng',
                'thiet_ke' => 'Thiết kế thể thao',
                'tienich_antoan' => 'Hệ thống giảm xóc hiệu quả',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 9,
                'hinh_anh' => 'https://images.autofun.vn/file1/108fb6bd72614bcaa7a3ed4829d86072_800.png',
                'bien_so' => null,
                'dong_xe' => 'Xe tay ga',
                'ten_xe' => 'SH160',
                'gia' => 98000000,
                'mau_sac' => 'Đỏ, Trắng',
                'so_khung' => 'KH876543',
                'so_may' => 'SM667788',
                'loai_xe' => '2',
                'tinh_nang' => 'Phanh ABS, Động cơ mạnh mẽ',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế sang trọng',
                'tienich_antoan' => 'Chống trộm, khóa an toàn',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 10,
                'hinh_anh' => 'http://media.vietq.vn/files/lehoa/2017/10/29/xe-tay-ga-1.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe tay ga',
                'ten_xe' => 'Vision 110',
                'gia' => 30000000,
                'mau_sac' => 'Đen, Trắng',
                'so_khung' => 'KH123456',
                'so_may' => 'SM998877',
                'loai_xe' => '2',
                'tinh_nang' => 'Động cơ 110cc, Phanh đĩa',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế thanh lịch',
                'tienich_antoan' => 'Chống trộm, khóa an toàn',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 11,
                'hinh_anh' => 'https://ssl.latcdn.com/img/95liUzSee-mau-xe-honda-air-blade-1-ba85.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe tay ga',
                'ten_xe' => 'Airblade 160',
                'gia' => 55000000,
                'mau_sac' => 'Đỏ, Xanh',
                'so_khung' => 'KH112233',
                'so_may' => 'SM667788',
                'loai_xe' => '2',
                'tinh_nang' => 'Phanh ABS, Động cơ mạnh mẽ',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế thể thao',
                'tienich_antoan' => 'Hệ thống giảm xóc hiệu quả',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 12,
                'hinh_anh' => 'https://arenamotosikal.com/wp-content/uploads/2022/05/2022-Honda-Lead-125-Thailand-001.jpeg',
                'bien_so' => null,
                'dong_xe' => 'Xe tay ga',
                'ten_xe' => 'Lead 125',
                'gia' => 42000000,
                'mau_sac' => 'Đỏ, Xám',
                'so_khung' => 'KH445566',
                'so_may' => 'SM223344',
                'loai_xe' => '2',
                'tinh_nang' => 'Động cơ 125cc, Phanh đĩa',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế hiện đại',
                'tienich_antoan' => 'Hệ thống an toàn ABS',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 13,
                'hinh_anh' => 'https://media.vov.vn/sites/default/files/styles/large/public/2021-12/phien_ban_the_thao_xe_do_den.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe côn tay',
                'ten_xe' => 'Winner X',
                'gia' => 60000000,
                'mau_sac' => 'Đen, Đỏ',
                'so_khung' => 'KH998877',
                'so_may' => 'SM334455',
                'loai_xe' => '3',
                'tinh_nang' => 'Động cơ 150cc, Phanh đĩa',
                'cong_nghe' => 'Công nghệ phun xăng điện tử',
                'thiet_ke' => 'Thiết kế thể thao',
                'tienich_antoan' => 'Chống trộm, khóa an toàn',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 14,
                'hinh_anh' => 'https://img.tinxe.vn/resize/1000x-/2021/01/12/XForF7yt/mau-xe-honda-cbr150r-2021-1-719c.jpg',
                'bien_so' => null,
                'dong_xe' => 'Xe côn tay',
                'ten_xe' => 'CBR150R',
                'gia' => 80000000,
                'mau_sac' => 'Đỏ, Xám',
                'so_khung' => 'KH223344',
                'so_may' => 'SM556677',
                'loai_xe' => '3',
                'tinh_nang' => 'Phanh đĩa, Động cơ mạnh mẽ',
                'cong_nghe' => 'Công nghệ tiết kiệm nhiên liệu',
                'thiet_ke' => 'Thiết kế thể thao',
                'tienich_antoan' => 'Hệ thống chống trộm',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 15,
                'hinh_anh' => 'https://cdn.honda.com.vn/e-motorbike-versions/Image360/October2024/1729582463/7.png',
                'bien_so' => null,
                'dong_xe' => 'Xe điện',
                'ten_xe' => 'ICON e',
                'gia' => 45000000,
                'mau_sac' => 'Đen, Trắng',
                'so_khung' => 'KH667788',
                'so_may' => 'SM998877',
                'loai_xe' => '4',
                'tinh_nang' => 'Phanh ABS, Động cơ điện',
                'cong_nghe' => 'Công nghệ tiết kiệm năng lượng',
                'thiet_ke' => 'Thiết kế hiện đại',
                'tienich_antoan' => 'Hệ thống an toàn điện',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ],
            [
                'id_xe' => 16,
                'hinh_anh' => 'https://cdn.honda.com.vn/e-motorbike-versions/Image360/October2024/1729590859/7.png',
                'bien_so' => null,
                'dong_xe' => 'Xe điện',
                'ten_xe' => 'CUV e',
                'gia' => 50000000,
                'mau_sac' => 'Trắng, Đen',
                'so_khung' => 'KH223344',
                'so_may' => 'SM667788',
                'loai_xe' => '4',
                'tinh_nang' => 'Động cơ điện, Phanh ABS',
                'cong_nghe' => 'Công nghệ tiết kiệm năng lượng',
                'thiet_ke' => 'Thiết kế tối giản',
                'tienich_antoan' => 'Hệ thống an toàn điện',
                'created_at' => '2024-11-26 14:18:16',
                'updated_at' => '2024-11-26 14:18:16',
            ]
        ]);
    }
}
